### PR TITLE
Fixed panic due to timing issue on ClientStream.Context()

### PR DESCRIPTION
**Pull request by pracucci**
In [Cortex](https://github.com/cortexproject/cortex) we use the `OpenTracingStreamClientInterceptor()`. Tonight we got an incident where some Cortex processes started to panic with the following stack trace:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x9f5afb]

goroutine 1097207 [running]:
google.golang.org/grpc/internal/transport.(*Stream).Context(...)
	/go/src/github.com/cortexproject/cortex/vendor/google.golang.org/grpc/internal/transport/transport.go:398
google.golang.org/grpc.(*clientStream).Context(0xc03c5157a0, 0xc0000a2bf0, 0xc000a5e7b0)
	/go/src/github.com/cortexproject/cortex/vendor/google.golang.org/grpc/stream.go:581 +0x3b
github.com/opentracing-contrib/go-grpc.newOpenTracingClientStream.func2(0xc03c6e0000, 0x2ad68c0, 0xc00f3e7000, 0xc041a5a820)
	/go/src/github.com/cortexproject/cortex/vendor/github.com/opentracing-contrib/go-grpc/client.go:159 +0x49
created by github.com/opentracing-contrib/go-grpc.newOpenTracingClientStream
	/go/src/github.com/cortexproject/cortex/vendor/github.com/opentracing-contrib/go-grpc/client.go:154 +0x13c
```

We learned that `cs.Context()` may panic if the underlying `clientStream.attempt.s` is `nil`. While we can quickly reproduce this issue in production, we haven't been able to reproduce it locally, so investigating it is non trivial.

However, after some investigation, it looks like to be caused due to a (possibly) timing issue in `newOpenTracingClientStream()`. When the goroutine inside that function is executed, it's not actually guaranteed that `cs` is still valid.

In this PR I'm proposing to grab `cs.Context()` synchronously and then use it in the deferred finish function and goroutine. We rolled out this change in our production environment and it fixes the issue.

What do you think?

### CODE REVIEW

**Comment by pracucci** [comment]
@austinlparker Would you have time to review this?

**Review by austinlparker — APPROVED** [review]

**Comment by austinlparker** [comment]
Just as an FYI, as OpenTelemetry Tracing 1.0 has been finalized, we'll be encouraging opentracing users to adopt opentelemetry in the near future as the language releases a stable 1.0

**Comment by pracucci** [comment]
> Just as an FYI, as OpenTelemetry Tracing 1.0 has been finalized, we'll be encouraging opentracing users to adopt opentelemetry in the near future as the language releases a stable 1.0

Ok, will do. Thanks a lot for getting back on this PR 🙏

**Comment by bboreham** [comment]
Personally I find it very challenging to use the OpenTelemetry packages because names keep moving around and there is no good documentation for developers to get started.

**Pull request merged**
