### PR TITLE
add Apache 2 license

### PR DESCRIPTION
**Pull request by dholbach**
closes: #3

### CODE REVIEW

**Comment by dholbach** [comment]
Who else needs to review and :+1: this?

**Comment by tamalsaha** [comment]
Can this pr be merged? We would also like to see a LICNESE for this repo.

**Comment by dholbach** [comment]
@fho @bboreham @mmoustai Pinging all contributors I can see on https://github.com/opentracing-contrib/go-grpc/graphs/contributors.

**Comment by fho** [comment]
Fine for me :+1:

**Comment by sidh** [comment]
> @fho @bboreham @mmoustai Pinging all contributors I can see on https://github.com/opentracing-contrib/go-grpc/graphs/contributors.

This blocks us from using this repo. :(

So yeah, would very much like the addition of a license.

**Comment by bboreham** [comment]
SGTM.

**Comment by dholbach** [comment]
According to #3 we still need :+1: from @kcamenzind @bhs @hzariv?

**Comment by sidh** [comment]
Any news on this?

**Comment by sidh** [comment]
Awesome! Just two more please! @kcamenzind @hzariv

**Comment by sidh** [comment]
Aaaaand one more! @kcamenzind

**Comment by dholbach** [comment]
Looks like this can be merged now, right?

**Comment by sidh** [comment]
> Looks like this can be merged now, right?

Looks like it.

**Comment by sidh** [comment]
Need someone with write access to merge it. @austinlparker may be?

**Comment by sidh** [comment]
Can anyone merge it?

**Comment by sidh** [comment]
Anyone with write access? @fho @bboreham @rnburn @mmoustai @austinlparker 

Sorry for pinging everyone :|

**Comment by sidh** [comment]
Anyone? @fho @bboreham @rnburn @mmoustai @austinlparker

**Comment by austinlparker** [comment]
sorry for the delay!

**Pull request merged**
